{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "andy.serviceAccountName" . }}
  labels:
{{ include "andy.labels" . | nindent 4 }}
{{- end -}}
